### ISSUE TITLE
Using b.require with react and react-dom results in an error

### ISSUE THREAD

**Issue by casr** [browserify/tinyify#16]
> browserify -r react -r react-dom -p tinyify

    /.../node_modules/tinyify/node_modules/common-shakeify/index.js:222
      return row[kDuplicates] || []
                ^
    
    TypeError: Cannot read property 'Symbol(duplicates)' of undefined
        at getDuplicates (/.../node_modules/tinyify/node_modules/common-shakeify/index.js:222:13)
        at analyzer.modules.forEach (/.../node_modules/tinyify/node_modules/common-shakeify/index.js:121:21)
        at Map.forEach (<anonymous>)
        at DestroyableTransform.onend [as _flush] (/.../node_modules/tinyify/node_modules/common-shakeify/index.js:118:22)
        at DestroyableTransform.prefinish (/.../node_modules/readable-stream/lib/_stream_transform.js:138:10)
        at emitNone (events.js:106:13)
        at DestroyableTransform.emit (events.js:208:7)
        at prefinish (/.../node_modules/readable-stream/lib/_stream_writable.js:619:14)
        at finishMaybe (/.../node_modules/readable-stream/lib/_stream_writable.js:627:5)
        at endWritable (/.../node_modules/readable-stream/lib/_stream_writable.js:638:3)

It appears to only happen when I use them both; if I `-r` them separately then it works fine. I tried it with some simpler packages such as `once` and `xtend` together and that appeared to work just fine.

The package.json:

    {
      "private": true,
      "scripts": {
        "test": "browserify -r react -r react-dom -p tinyify"
      },
      "dependencies": {
        "react": "16.6.3",
        "react-dom": "16.6.3"
      },
      "devDependencies": {
        "browserify": "16.2.3",
        "tinyify": "2.4.3"
      }
    }

**Comment by casr** [comment]
I don't believe it is. I have an API example that uses common-shakeify 0.5.2 that results in a similar error:

```js
const commonModules = ['react', 'react-dom']

const g = { global: true }
const commonB = browserify()
commonB.require(commonModules)
commonB.transform('unassertify', g)
commonB.transform(envify({ _: 'purge', NODE_ENV: 'production' }), g)
commonB.transform('uglifyify', g)
commonB.plugin('common-shakeify')
commonB.plugin('browser-pack-flat/plugin')

const commonBundle = commonB.bundle().pipe(require('minify-stream')({ sourceMap: false }))
```

**Comment by goto-bus-stop** [comment]
OK, thanks for checking :+1:

**Comment by goto-bus-stop** [comment]
Ah right, it's to do with how `row.file` and `row.id` are set when using --require, common-shakeify doesn't pick the right property I think…

it reproduces with just common-shakeify: `browserify -r react -r react-dom -p common-shakeify`

going to try github's new transfer feature on this issue then!
